NAME := blemesh_pts

$(NAME)_MBINS_TYPE := app
$(NAME)_VERSION := 0.0.1
$(NAME)_SUMMARY :=
$(NAME)_SOURCES     := main.c

$(NAME)_INCLUDES    := ../../../../network/bluetooth/bt_host/include \
                       ../../../../network/bluetooth/bt_host/core/include \
					   ../../../../network/bluetooth/bt_mesh/inc     \
					   ../../../../network/bluetooth/bt_mesh/mesh_model \
					   ../../../../network/bluetooth/bt_mesh/vendor_model \
					   ../../../../genie_app

ble = 1
en_bt_smp = 1

$(NAME)_COMPONENTS  += bluetooth.bt_mesh yloop cli


# Host configurations
GLOBAL_DEFINES += CONFIG_BLUETOOTH
GLOBAL_DEFINES += CONFIG_BT_SMP
GLOBAL_DEFINES += CONFIG_BT_TINYCRYPT_ECC
GLOBAL_DEFINES += CONFIG_BT_CONN
#GLOBAL_DEFINES += CONFIG_BT_CENTRAL
GLOBAL_DEFINES += CONFIG_BT_PERIPHERAL
GLOBAL_DEFINES += CONFIG_BLE_50
GLOBAL_DEFINES += CONFIG_BT_HCI_VS_EXT

# Mesh function select
GLOBAL_DEFINES += CONFIG_BT_MESH
GLOBAL_DEFINES += CONFIG_BT_MESH_PROV
#GLOBAL_DEFINES += CONFIG_BT_MESH_PROVISIONER
GLOBAL_DEFINES += CONFIG_BT_MESH_PB_ADV
GLOBAL_DEFINES += CONFIG_BT_MESH_PB_GATT
GLOBAL_DEFINES += CONFIG_BT_MESH_GATT_PROXY
GLOBAL_DEFINES += CONFIG_BT_MESH_RELAY
GLOBAL_DEFINES += CONFIG_BT_MESH_FRIEND
GLOBAL_DEFINES += CONFIG_BT_MESH_LOW_POWER
GLOBAL_DEFINES += CONFIG_BT_MESH_SHELL
GLOBAL_DEFINES += CONFIG_BT_MESH_BQB
GLOBAL_DEFINES += CONFIG_BT_MESH_IV_UPDATE_TEST

# Mesh foundation model select
GLOBAL_DEFINES += CONFIG_BT_MESH_CFG_CLI
GLOBAL_DEFINES += CONFIG_BT_MESH_CFG_SRV
GLOBAL_DEFINES += CONFIG_BT_MESH_HEALTH_CLI
GLOBAL_DEFINES += CONFIG_BT_MESH_HEALTH_SRV
GLOBAL_DEFINES += CONFIG_BT_MESH_GEN_ONOFF_CLI
GLOBAL_DEFINES += CONFIG_BT_MESH_GEN_BATTERY_CLI
GLOBAL_DEFINES += CONFIG_BT_MESH_GEN_LEVEL_CLI
GLOBAL_DEFINES += CONFIG_BT_MESH_GEN_DEF_TRANS_TIME_CLI
GLOBAL_DEFINES += CONFIG_BT_MESH_GEN_POWER_ONOFF_CLI
GLOBAL_DEFINES += CONFIG_BT_MESH_GEN_POWER_LEVEL_CLI
GLOBAL_DEFINES += CONFIG_BT_MESH_GEN_LOCATION_CLI
GLOBAL_DEFINES += CONFIG_BT_MESH_GEN_PROP_CLI
#GLOBAL_DEFINES += CONFIG_BT_MESH_SENSOR_CLI
#GLOBAL_DEFINES += CONFIG_BT_MESH_TIME_CLI
GLOBAL_DEFINES += CONFIG_BT_MESH_SCENE_CLI
GLOBAL_DEFINES += CONFIG_BT_MESH_SCHEDULER_CLI
GLOBAL_DEFINES += CONFIG_BT_MESH_LIGHT_LIGHTNESS_CLI
GLOBAL_DEFINES += CONFIG_BT_MESH_LIGHT_CTL_CLI
GLOBAL_DEFINES += CONFIG_BT_MESH_LIGHT_HSL_CLI
#GLOBAL_DEFINES += CONFIG_BT_MESH_LIGHT_XYL_CLI
GLOBAL_DEFINES += CONFIG_BT_MESH_LIGHT_LC_CLI

# Mesh debug message enable
GLOBAL_DEFINES += USE_BT_MESH_CUSTOM_LOG

#GLOBAL_DEFINES += CONFIG_INIT_STACKS
#GLOBAL_DEFINES += CONFIG_PRINTK
#GLOBAL_DEFINES += CONFIG_BT_GATT_CLIENT

GLOBAL_INCLUDES += ../

MESH_MODEL_LIGHTNESS_SRV = 1

