#ifndef BLE_CONFIG
#define BLE_CONFIG

#define CONFIG_BT_HCI_TX_STACK_SIZE 1024
#define CONFIG_BT_RX_STACK_SIZE 2048
#define CONFIG_BT_MESH_ADV_PRIO 14
#define CONFIG_BT_HCI_TX_PRIO  15
#define CONFIG_BT_RX_PRIO 18
#define AOS_DEFAULT_APP_PRI 17
#endif

