
$(NAME)_SOURCES += bt_controller/hci/hci_driver.c \
				   bt_controller/hci/hci.c

GLOBAL_DEFINES += CONFIG_BT_OBSERVER
GLOBAL_DEFINES += CONFIG_BT_BROADCASTER
GLOBAL_DEFINES += CONFIG_DEVICE_POWER_MANAGEMENT
GLOBAL_DEFINES += CONFIG_BT_CTLR_LE_ENC
#GLOBAL_DEFINES += CONFIG_BT_CTLR_PHY_2M
GLOBAL_DEFINES += CONFIG_BT_CTLR_MIN_USED_CHAN
GLOBAL_DEFINES += CONFIG_BT_CTLR_PHY
GLOBAL_DEFINES += CONFIG_BT_CTLR_CHAN_SEL_2
GLOBAL_DEFINES += CONFIG_BT_CTLR_CONN_PARAM_REQ
GLOBAL_DEFINES += CONFIG_BT_CTLR_TIFS_HW
GLOBAL_DEFINES += CONFIG_BT_HCI_VS_EXT
GLOBAL_DEFINES += CONFIG_CONTROLLER_IN_ONE_TASK